name: CI SDLC
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4.28'
          coverage: none
          ini-values: memory_limit=-1
          extensions: mbstring, intl
      - name: Download deps
        run: composer update --no-interaction --no-progress
      - name: Download PHPStan
        run: composer require --dev phpstan/phpstan
      - name: Download larastan v1 (Laravel Framework 6.20.44)
        run: composer require nunomaduro/larastan:^1.0 --dev
      - name: Delete conflicting file
        run: rm -f database/migrations/2015_11_05_183749_image.php
      - name: Execute PHPStan
        run: COMPOSER_MEMORY_LIMIT=-1 vendor/bin/phpstan analyze --no-progress --error-format=github -l 0 -c phpstan.neon . 
          
